networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
#      - ./migr-postgresql.conf:/etc/postgresql/postgresql.conf
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=openupgrade11
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=odoo.dy
      - VIRTUAL_PORT=8069
      - LIMIT_TIME_CPU=6000000
      - LIMIT_TIME_REAL=12000000
      - LIMIT_MEMORY_SOFT=5147483648
      - LIMIT_MEMORY_HARD=5684354560
      - ADDONS_PATH=/odoo/local-src,/odoo/src/addons,/odoo/external-src/bank-payment,/odoo/external-src/intrastat,/odoo/external-src/web,/odoo/external-src/server-tools,/odoo/external-src/account-invoicing,/odoo/external-src/product-attribute,/odoo/external-src/l10n-france,/odoo/external-src/l10n-brazil,odoo/external-src/partner-contact
    links:
      - db
#    ports: 
#      - 8069:8069
    networks:
      default:
        aliases:
          - odoo.dy
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
volumes:
  py3o_tmp: null
